### ISSUE TITLE
Nespravne GPS koordinaty

### ISSUE THREAD

**Issue by lukasgejdos** [SlovakNationalGallery/register-architektury#123]
Zdravicko, urcite to nie je chyba v kode, ale neviem, kde to mam poslat :) Narazil som na nespravne umiestnenie objektu na mape:
URL: https://www.register-architektury.sk/objekt/149-statna-banka-a-poistovna-v-liptovskom-mikulasi
![image](https://user-images.githubusercontent.com/9935013/95134765-b97bff00-0763-11eb-8590-1d946dc522a2.png)

Inak skvely projekt, drzim palce v dalsom vyvoji!

**Comment by eronisko** [comment]
Dakujeme za bug report! Posunul som dalej (na SAV), dam vediet ked to bude opravene.

**Comment by lukasgejdos** [comment]
Nie je zac, rado sa stalo :) Drzim palce s projektom!

**Comment by eronisko** [comment]
Opravene, este raz vdaka :)
